import Head from 'next/head'
import {Typography} from '@mui/material';

export default function Dashboard() {
	return (
		<>
			<Head>
				<title>Salud Digna - Nutricion</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<Typography variant={'h2'}>
					Dashboard Side
				</Typography>
			</main>
		</>
	)
}
