import Head from 'next/head'
import {Box} from '@mui/material';
import Nav from "@pages/dashboard/components/Nav";
import Clients from "@pages/dashboard/Clients";



export default function Dashboard() {
	return (
		<>
			<Head>
				<title>Salud Digna - Nutricion</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main style={{ height:'100vh' }} >
				<Box sx={{ width: '100%', height:'100%', display:'flex' }} >
					<Nav/>
					<Clients/>
				</Box>
			</main>
		</>
	)
}
