import Head from 'next/head'
import {Box, Typography} from '@mui/material';

export default function App() {
	return (
		<>
			<Head>
				<title>Salud Digna - Nutricion</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<Box
					sx={{
						height:'50px',
						width:'100%',
					}}
					className={'ph-img'}
					>
					Salud digna logo
				</Box>

				<Typography variant={'h2'}>
					App Side
				</Typography>
			</main>
		</>
	)
}
