import Head from 'next/head'
import {useState} from "react";
import {Box, Tab, Tabs} from '@mui/material';
import PhoneAndroidIcon from '@mui/icons-material/PhoneAndroid';


export default function App() {
	const [value, setValue] = useState(0);

	const handleChange = (event, newValue) => {
		setValue(newValue);
	};

	return (
		<>
			<Head>
				<title>Salud Digna - Nutricion</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main>
				<Box
					sx={{
						height:'50px',
						width:'100%',
					}}
					className={'ph-img'}
					>
					Salud digna logo
				</Box>
				{
					value === 0 &&
					<Box>
						Alpha
					</Box>
				}
				{
					value === 1 &&
					<Box>
						Beta
					</Box>
				}
				{
					value === 2 &&
					<Box>
						Gamma
					</Box>
				}
				<Box
					sx={{
						position:'absolute',
						bottom:0,
						width:'100%'
					}}>

					<Tabs
						variant="fullWidth"
						value={value}
						onChange={handleChange}
						aria-label="icon label tabs example">
						<Tab icon={<PhoneAndroidIcon />} label="Alpha" />
						<Tab icon={<PhoneAndroidIcon />} label="Beta" />
						<Tab icon={<PhoneAndroidIcon />} label="Gamma" />
					</Tabs>
				</Box>
			</main>
		</>
	)
}
